global:
  scrape_interval: 15s # Intervalle de récupération par défaut

scrape_configs:
  - job_name: 'prometheus'
    # Configuration pour que Prometheus se surveille lui-même
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ids2-agent'
    # L'agent Python expose ses métriques sur le port 9100
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    # cAdvisor pour la surveillance des conteneurs Docker
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    # Node Exporter pour la surveillance de l'hôte Raspberry Pi
    static_configs:
      - targets: ['node_exporter:9100']
